#Choose the input file for main (create.txt, new.txt, vote.txt, disqualify.txt...)
#set(input create.txt)
#set(input new.txt)
#set(input vote.txt)
#set(input remove.txt)
#set(input disqualify.txt)
set(input winners.txt)
